### ISSUE TITLE
UpdateDocumentById endpoint throws exception

### ISSUE THREAD

**Issue by jakdan99** [cph-cachet/carp-webservices-spring#37]
```
{
    "statusCode": 500,
    "exception": "java.lang.reflect.UndeclaredThrowableException",
    "message": "Cannot deserialize value of type `com.fasterxml.jackson.databind.node.ObjectNode` from String value (token `JsonToken.VALUE_STRING`)\n at [Source: UNKNOWN; byte offset: #UNKNOWN]",
    "path": "PUT /api/studies/340ca3e0-07de-40b1-af2d-f49ae57a015a/documents/151"
}
```

**Comment by xelahalo** [comment]
## How to reproduce

1. Go to dev.carp.dk
2. Click on any study that is live
3. Go to resources page
4. Upload any resource (other, with a .json extension)
5. Edit the resource
6. Hit Update -> There will be a snackbar that says what the issue is.

![image](https://github.com/cph-cachet/carp-webservices-spring/assets/38317944/e328e5f4-bfe9-493a-8c5b-e7736ab5f76a)

**Comment by yuanchen233** [comment]
The request sent here is a string, it should be a proper JSON object instead.
![Image](https://github.com/cph-cachet/carp-webservices-spring/assets/10835085/44775c0b-9017-4c2c-8d42-2d76217a19e5)


Example below:
![Image](https://github.com/cph-cachet/carp-webservices-spring/assets/10835085/91a87ded-55cb-443f-bfac-68660d901094)
Should be:
![Image](https://github.com/cph-cachet/carp-webservices-spring/assets/10835085/5481c741-d6b7-44a0-aae1-1d905c4abd4a)

**Comment by jakdan99** [comment]
Tried it out, looks like it is working
